-- 2진수로 변환했을 때 A가 B에 완전히 포함되어야 한다는 점
-- 비트 연산자 & 로 해결

SELECT E1.ID, E1.GENOTYPE, E2.GENOTYPE
FROM ECOLI_DATA E1 JOIN ECOLI_DATA E2
    ON E1.PARENT_ID = E2.ID
WHERE (E2.GENOTYPE & E1.GENOTYPE) = E2.GENOTYPE
ORDER BY ID
