/* 
JOIN, 서브쿼리 둘 다 생각났는데
둘 다 오류 없이 구현되는지 테스트 해보고 싶었다.

NOT IN () 안에 NULL이 포함 되면 아무것도 안 나옴
*/

/* SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID NOT IN (
    SELECT DISTINCT(PARENT_ITEM_ID)
    FROM ITEM_TREE
    WHERE PARENT_ITEM_ID IS NOT NULL
)
ORDER BY ITEM_ID DESC */

SELECT I.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO I LEFT OUTER JOIN ITEM_TREE T
    ON I.ITEM_ID = T.PARENT_ITEM_ID
WHERE T.PARENT_ITEM_ID IS NULL
ORDER BY I.ITEM_ID DESC
