-- JOIN 조건에 YEAR 함수 적용이 가능한 걸 깨달음

SELECT Y.YEAR, Y.M - SIZE_OF_COLONY AS YEAR_DEV, ID
FROM ECOLI_DATA E JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS M
    FROM ECOLI_DATA
    GROUP BY YEAR
) AS Y ON Y.YEAR = YEAR(E.DIFFERENTIATION_DATE)
ORDER BY YEAR, YEAR_DEV
